name: 'lesfourcasters_dbt'
version: '1.0.0'
config-version: 2

profile: 'lesfourcasters_dbt'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lesfourcasters_dbt:
    staging:
      materialized: table
      tags: ['staging']
    intermediate:
      materialized: table
      tags: ['intermediate']
    mart:
      materialized: table
      tags: ['mart']

vars:
  start_date: '2020-01-01'