lesfourcasters_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: newfourcasters
      dataset: lesfourcasters_dbt
      location: US
      threads: 4
    ci:
      type: bigquery
      method: service-account
      project: newfourcasters
      keyfile: /tmp/gcp-key.json
      dataset: lesfourcasters_dbt
      location: US
      threads: 4